apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
spec:
  snapshotClassName: csi-hostpath-snapclass
  source:
    name: hpvc
    kind: PersistentVolumeClaim
